# Generated by Django 5.1 on 2024-09-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='uvp',
        ),
    ]
