# Generated by Django 5.1 on 2024-09-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='user',
        ),
        migrations.AddField(
            model_name='indicador',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='server.profile'),
        ),
    ]
