# Generated by Django 5.1 on 2024-09-06 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_rename_user_account_alter_account_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dolar_intercambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('euro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ipc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ivp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imacec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('libra_cobre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tasa_desempleo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bitcoin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
